#!/usr/bin/env node
/**
 * env:sync
 *
 * Copies all EXPO_PUBLIC_* and NEXT_PUBLIC_* variables from the root
 * .env.local (preferred) or .env into the per-app environment files:
 *   - apps/mobile/.env
 *   - apps/web/.env.local
 *
 * This lets you maintain a single source of truth at the repo root
 * while still supporting "cd apps/web && pnpm dev" and "cd apps/mobile && pnpm dev".
 *
 * Usage:
 *   pnpm env:sync
 *
 * After changing client keys in root .env.local, just run this again.
 */
const fs = require('fs');
const path = require('path');

const ROOT = process.cwd();
const ENV_LOCAL = path.join(ROOT, '.env.local');
const ENV = path.join(ROOT, '.env');

const MOBILE_ENV = path.join(ROOT, 'apps/mobile/.env');
const WEB_ENV = path.join(ROOT, 'apps/web/.env.local');

function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) return {};
  const content = fs.readFileSync(filePath, 'utf8');
  const vars = {};
  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    let key = line.slice(0, eq).trim();
    let val = line.slice(eq + 1).trim();
    // strip surrounding quotes
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    vars[key] = val;
  }
  return vars;
}

function filterClientVars(allVars) {
  const result = {};
  for (const [k, v] of Object.entries(allVars)) {
    if (k.startsWith('EXPO_PUBLIC_') || k.startsWith('NEXT_PUBLIC_')) {
      result[k] = v;
    }
  }
  return result;
}

function writeEnvFile(targetPath, vars, commentHeader) {
  const lines = [];
  if (commentHeader) {
    lines.push(commentHeader);
    lines.push('');
  }
  // Sort: EXPO first, then NEXT, alpha within groups
  const sortedKeys = Object.keys(vars).sort((a, b) => {
    const aIsExpo = a.startsWith('EXPO_PUBLIC_') ? 0 : 1;
    const bIsExpo = b.startsWith('EXPO_PUBLIC_') ? 0 : 1;
    if (aIsExpo !== bIsExpo) return aIsExpo - bIsExpo;
    return a.localeCompare(b);
  });

  for (const key of sortedKeys) {
    let value = vars[key];
    // Re-quote values that contain whitespace or special characters
    const needsQuotes = /[\s"'#\\]/.test(value) || value === '';
    if (needsQuotes) {
      value = `"${value.replace(/"/g, '\\"')}"`;
    }
    lines.push(`${key}=${value}`);
  }

  fs.mkdirSync(path.dirname(targetPath), { recursive: true });
  fs.writeFileSync(targetPath, lines.join('\n') + '\n', 'utf8');
  console.log(`   ✓ ${Object.keys(vars).length} vars → ${path.relative(ROOT, targetPath)}`);
}

function main() {
  console.log('\n🔄 env:sync — syncing client public vars from root to web & mobile...\n');

  let rootVars = parseEnvFile(ENV_LOCAL);
  if (Object.keys(rootVars).length === 0) {
    console.log('   .env.local missing or empty — falling back to .env');
    rootVars = parseEnvFile(ENV);
  }

  const clientVars = filterClientVars(rootVars);

  if (Object.keys(clientVars).length === 0) {
    console.error('❌ No EXPO_PUBLIC_* or NEXT_PUBLIC_* keys found in root env files.');
    console.error('   Make sure your .env.local (or .env) at the project root contains the client variables.');
    process.exit(1);
  }

  const mobileVars = {};
  const webVars = {};
  for (const [k, v] of Object.entries(clientVars)) {
    if (k.startsWith('EXPO_PUBLIC_')) mobileVars[k] = v;
    if (k.startsWith('NEXT_PUBLIC_')) webVars[k] = v;
  }

  const header = '# Auto-generated by `pnpm env:sync`\n# Edit the corresponding values in the ROOT .env.local (or .env) and re-run the command.';

  writeEnvFile(MOBILE_ENV, mobileVars, header);
  writeEnvFile(WEB_ENV, webVars, header);

  console.log('\n✅ Client environment variables synced successfully.');
  console.log('   Web and mobile will now see the same Supabase / API config you maintain at the root.\n');
}

main();
